{% set name = "openbabel" %}
{% set version = "3.0.0.post158" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openbabel/openbabel
  git_rev: d0c4e44c6e03edf46ee138d2f7709043d79e1308
  patches:
    - fix_babel_test_paths.diff
    - fix_backinserter.diff
    - fix_data_path.diff
    - fix_library_path_search.diff

build:
  number: 0
  skip: true  # [py<36 or osx or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - swig
  host:
    - python
    - zlib
    - eigen
    - libxml2
    - cairo
    - rapidjson
  run:
    - python

test:
  imports:
    - openbabel.openbabel
    - openbabel.pybel
  commands:
    - obabel --help
    - obabel -:c1ccccc1 --gen3d -omol2
    - obabel -:c1ccccc1 --gen3d -oinchi
    - obabel -:c1ccccc1 -opng -O img.png

about:
    home: http://openbabel.org/
    license: GPLv2
    license_family: GPL
    license_file: COPYING
    summary: "A chemical toolbox designed to speak the many languages of chemical data"
    description: |
      Open Babel is a chemical toolbox designed to speak the many languages of chemical
      data. It's an open, collaborative project allowing anyone to search, convert,
      analyze, or store data from molecular modeling, chemistry, solid-state materials,
      biochemistry, or related areas.
    doc_url: http://openbabel.org/
    dev_url: https://github.com/openbabel/openbabel
